@extends('welcome')
@section('content')
@push('styles')
      <link rel="stylesheet" href="{{ asset('/css/tools.css') }}">
@endpush
    <div class="container-setup">
        <h6 class="content-title-detail"><a href="{{ route('home') }}"
                style="color: #2254AB; text-decoration: underline;">Trang chủ</a><i class="bi bi-chevron-right"></i> <a
                style="color: #2254AB; text-decoration: underline;" href="">Tiện ích</a> <i
                class="bi bi-chevron-right"></i> <span>
                Xem ngày tốt xấu</span></h6>

        <h1 class="content-title-home-lich">Xem ngày tốt xấu</h1>

        <div class="row mt-4">
            <div class="col-lg-4 col-md-12 col-sm-12 mb-4">
                <div class="card border-0 shadow-lg font-tools" >
                    <div class="card-body p-4">
                        <div class="card-title text-white fw-bold mb-3 title-tong-quan-h2-log">Thông tin người xem</div>
                        <p class="text-white mb-4" style="opacity: 0.9; font-size: 14px;">Bạn hãy nhập thông tin vào ô dưới
                            đây để xem ngày tốt xấu</p>

                        <form id="totXauForm">
                            <div class="mb-3">
                                <div class="input-group">
                                    <input type="text" class="form-control" id="ngayXem" placeholder="Chọn ngày" readonly
                                        style="border-radius: 10px; border: none; padding: 12px 45px 12px 15px; background-color: rgba(255,255,255,0.95); cursor: pointer;">
                                    <span class="input-group-text bg-transparent border-0"
                                        style="position: absolute; right: 15px; top: 50%; transform: translateY(-50%); z-index: 5;">
                                        <i class="bi bi-calendar3 text-muted"></i>
                                    </span>
                                </div>
                                <!-- Custom Calendar Popup -->
                                <div class="custom-calendar" id="customCalendar" style="display: none;">
                                    <div class="calendar-header-date">
                                        <button type="button" class="btn-nav" id="prevMonth"><i class="bi bi-chevron-left"></i></button>
                                        <span class="month-year" id="monthYear">October 2025</span>
                                        <button type="button" class="btn-nav" id="nextMonth"><i class="bi bi-chevron-right"></i></button>
                                    </div>
                                    <div class="calendar-weekdays">
                                        <div class="weekday">CN</div>
                                        <div class="weekday">T2</div>
                                        <div class="weekday">T3</div>
                                        <div class="weekday">T4</div>
                                        <div class="weekday">T5</div>
                                        <div class="weekday">T6</div>
                                        <div class="weekday">T7</div>
                                    </div>
                                    <div class="calendar-days" id="calendarDays">
                                        <!-- Days will be generated by JavaScript -->
                                    </div>
                                    <div class="calendar-footer">
                                        <button type="button" class="btn-calendar btn-clear" id="clearDate">Xóa</button>
                                        <button type="button" class="btn-calendar btn-today" id="todayDate">Hôm nay</button>
                                    </div>
                                </div>
                            </div>
                            <hr style="color: #FFFFFF66">
                            <div class="text-white fw-bold mb-3 title-tong-quan-h2-log">Khoảng thời gian cần xem</div>
                            <div class="mb-4">
                                <div class="input-group">
                                    <input type="text" class="form-control wedding_date_range" id="khoangNgay" placeholder="Chọn khoảng ngày (bôi đen để chọn)"
                                        style="border-radius: 10px; border: none; padding: 12px 45px 12px 15px; background-color: rgba(255,255,255,0.95); cursor: pointer;">
                                    <span class="input-group-text bg-transparent border-0"
                                        style="position: absolute; right: 15px; top: 50%; transform: translateY(-50%); z-index: 5; pointer-events: none;">
                                        <i class="bi bi-calendar3 text-muted"></i>
                                    </span>
                                </div>
                                <small class="text-white-50 d-block mt-2" style="font-size: 12px;">
                                    💡 Click vào ô trên, sau đó bôi đen từ ngày bắt đầu đến ngày kết thúc
                                </small>
                            </div>

                            <button type="submit" class="btn btn-light fw-bold w-100"
                                style="border-radius: 10px; padding: 12px; background-color: rgba(255,255,255,0.95); color: #357ABD; border: none;">
                                Xem Ngày Tốt
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-8 col-md-12 col-sm-12">
                <div class="d-flex flex-column align-items-center justify-content-center h-100 text-center">
                    <div class="mb-4">
                      <img src="{{ asset('/icons/defaild.png') }}" alt="defakd" class="img-fuild">
                    </div>
                    <p class="text-muted" style="font-size: 16px;">
                        Hiện chưa có thông tin, bạn vui lòng nhập thông tin để xem kết quả.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Global Calendar Popup for all date inputs -->
    <div class="global-calendar" id="globalCalendar" style="display: none;">
        <div class="calendar-header">
            <button type="button" class="btn-nav" id="globalPrevMonth">&lt;</button>
            <span class="month-year" id="globalMonthYear">Tháng 10 2025</span>
            <button type="button" class="btn-nav" id="globalNextMonth">&gt;</button>
        </div>
        <div class="calendar-weekdays">
            <div class="weekday">CN</div>
            <div class="weekday">T2</div>
            <div class="weekday">T3</div>
            <div class="weekday">T4</div>
            <div class="weekday">T5</div>
            <div class="weekday">T6</div>
            <div class="weekday">T7</div>
        </div>
        <div class="calendar-days" id="globalCalendarDays">
            <!-- Days will be generated by JavaScript -->
        </div>
        <div class="calendar-footer">
            <button type="button" class="btn-calendar btn-clear" id="globalClearDate">Xóa</button>
            <button type="button" class="btn-calendar btn-today" id="globalTodayDate">Hôm nay</button>
        </div>
    </div>

    {{-- Custom Calendar Module - Reusable --}}
    <script src="{{ asset('/js/custom-calendar.js?v=1.0') }}"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // ========== INITIALIZE CALENDARS ==========
            // Custom calendar cho Ngày Xem
            const ngayXemCalendar = new CustomCalendar({
                inputId: 'ngayXem',
                calendarId: 'customCalendar',
                defaultToToday: true
            });

            // Global calendar (nếu cần cho inputs khác)
            const globalCal = new GlobalCalendar('globalCalendar');

            // ========== FORM HANDLING ==========
            const form = document.getElementById('totXauForm');
            const khoangNgay = document.getElementById('khoangNgay');

            // Handle form submission
            form.addEventListener('submit', function(e) {
                e.preventDefault();

                const ngayXemValue = document.getElementById('ngayXem').value;

                // Validate Ngày Xem
                if (!ngayXemValue) {
                    alert('Vui lòng chọn ngày xem');
                    return;
                }

                // Validate Date Range
                if (!DateUtils.validateDateRange(khoangNgay.value)) {
                    return;
                }

                // Convert Vietnamese dates to ISO format for backend
                const ngayXemDate = DateUtils.parseVietnameseDate(ngayXemValue);
                const dateRange = DateUtils.parseDateRange(khoangNgay.value);

                // Process form data
                const formData = {
                    ngayXem: ngayXemDate ? DateUtils.formatDateValue(ngayXemDate) : '',
                    tuNgay: dateRange.start ? DateUtils.formatDateValue(dateRange.start) : '',
                    denNgay: dateRange.end ? DateUtils.formatDateValue(dateRange.end) : '',
                    khoangNgay: khoangNgay.value,
                    // Display values
                    ngayXemDisplay: ngayXemValue,
                    khoangNgayDisplay: khoangNgay.value
                };

                console.log('Form data:', formData);
                alert('Đã nhận thông tin:\nNgày xem: ' + ngayXemValue + '\nKhoảng ngày: ' + khoangNgay.value);

                // TODO: Submit to backend
                // fetch('/api/tot-xau', {
                //     method: 'POST',
                //     headers: { 'Content-Type': 'application/json' },
                //     body: JSON.stringify(formData)
                // });
            });
        });
    </script>
@endsection
